codecov:
  branch: master               # the branch to show by default

coverage:
  notify:
    slack:
      default:
        url: secret:Wkuy2qO70Y9V86VrhGcMc1AHs+blR5tt3egs58QZKgQy8uZaS6EAtyoHDTVcQLYjwOaU5VY1JBEVxt6zbZnSZ4n6rHHlozFxgScj9EagsLKsPP23RoktmtAgLmmzp0Hzt5M/Hlflx3Zr2nazh4EsKBVm3xxaFPe8BXSr3zjhQC4=
        threshold: 1%

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        target: auto           # specify the target coverage for each commit status
                               #   option: "auto" (must increase from parent commit or pull request base)
                               #   option: "X%" a static target percentage to hit
        threshold: 1%          # allowed to drop X% and still result in a "success" commit status
