module: Kitura
author: IBM & Kitura project contributors
github_url: https://github.com/Kitura/Kitura/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

